apiVersion: v1
kind: Namespace
metadata:
    name: node4

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: node4
  name: rest-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
       app: hyperledger       
       org: node4
    spec:
      # nodeSelector:
      #   # assume all org node can access to docker
      #   org: node4
      containers:
      - name: rest-api
        image: hyperledger/sawtooth-rest_api:latest
        ports:
          - containerPort: 8080
        command: 
        - bash
        - "-c"
        - |
          sawtooth-rest-api -C tcp://sawtooth:4004 --bind rest-api:8080

--- 

apiVersion: v1
kind: Service
metadata:
   namespace: node4
   name: rest-api
spec:
 selector:
   app: hyperledger      
   org: node4
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 8080
     targetPort: 8080
     nodePort: 30080









