# Copyright 2018 Agiletech Viet Nam
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "3"

services:

  # setup 3 settings transaction families
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: sawtooth-settings-tp        
    entrypoint: settings-tp -C tcp://validator:4004  

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: sawtooth-settings-tp-1        
    entrypoint: settings-tp -C tcp://validator-1:4004 

  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: sawtooth-settings-tp-2        
    entrypoint: settings-tp -C tcp://validator-2:4004 

  # setup 3 processors as transaction families
  processor:
    image: thanhtu/sawtooth-processor:latest
    container_name: sawtooth-processor        
    command: bash -c "sawtooth-processor -C tcp://validator:4004"

  processor-1:
    image: thanhtu/sawtooth-processor:latest
    container_name: sawtooth-processor-1        
    command: bash -c "sawtooth-processor -C tcp://validator-1:4004"

  processor-2:
    image: thanhtu/sawtooth-processor:latest
    container_name: sawtooth-processor-2        
    command: bash -c "sawtooth-processor -C tcp://validator-2:4004"

  # setup 3 validators, and 1 rest-api that connect to the first validator
  validator:
    image: thanhtu/sawtooth-validator-optimized:latest        
    container_name: sawtooth-validator
    expose:
      - 4004
      - 8800
    ports:
      - "34004:4004"        
    # command: /bin/bash        
    command: |
      bash -c "
        sawadm keygen --force && \
        sawadm genesis && \
        sawtooth-validator \
            --scheduler parallel \
            --bind network:tcp://eth0:8800 \
            --bind component:tcp://eth0:4004 \
            --endpoint tcp://validator:8800 \
            --peering dynamic \
            --network trust
      "

    stop_signal: SIGKILL

  validator-1:
      image: thanhtu/sawtooth-validator-optimized:latest
      container_name: sawtooth-validator-1
      expose:
        - 4004
        - 8800
      ports:
        - "14004:4004"           
      command: |
        bash -c "
          sawadm keygen --force && \
          sawtooth-validator \
              --bind network:tcp://eth0:8800 \
              --bind component:tcp://eth0:4004 \
              --endpoint tcp://validator-1:8800 \
              --peering dynamic \
              --seeds tcp://validator:8800 \
              --scheduler parallel \
              --network trust
        "      
      stop_signal: SIGKILL


  validator-2:
    image: thanhtu/sawtooth-validator-optimized:latest
    container_name: sawtooth-validator-2
    expose:
      - 4004
      - 8800
    ports:
      - "24004:4004"    
    command: |
      bash -c "
        sawadm keygen --force && \
        sawtooth-validator \
            --bind network:tcp://eth0:8800 \
            --bind component:tcp://eth0:4004 \
            --endpoint tcp://validator-2:8800 \
            --peering dynamic \
            --seeds tcp://validator:8800 \
            --scheduler parallel \
            --network trust
      "    
    stop_signal: SIGKILL      


  rest-api:
    image: hyperledger/sawtooth-rest_api:latest
    container_name: sawtooth-rest-api
    ports:
      - "38080:8080"
    # no need to re-create rest-api for validator
    # depends_on:
    #   - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8080


  # rest-api-1:
  #   image: hyperledger/sawtooth-rest_api:latest
  #   container_name: sawtooth-rest-api-1
  #   ports:
  #     - "38081:8081"
  #   # no need to re-create rest-api for validator
  #   # depends_on:
  #   #   - validator
  #   entrypoint: sawtooth-rest-api -C tcp://validator-1:4004 --bind rest-api-1:8081
