apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sawtooth-test
  name: validator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: validator
    spec:      
      containers:
      - name: validator
        image: thanhtu/sawtooth-validator-optimized:latest
        ports:
        - containerPort: 4004
        command: 
        - bash
        - "-c"
        - |
          sawadm keygen --force && \
            sawadm genesis && \
            sawtooth-validator \
                -vv \
                --scheduler parallel \
                --bind network:tcp://eth0:8800 \
                --bind component:tcp://eth0:4004 \
                --endpoint tcp://validator:8800 \
                --peering dynamic \
                --scheduler parallel \
                --network trust

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sawtooth-test
  name: validator-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: validator-1
    spec:      
      containers:
      - name: validator-1
        image: thanhtu/sawtooth-validator-optimized:latest
        ports:
        - containerPort: 4004
        command: 
        - bash
        - "-c"
        - |
          sawadm keygen --force && \
            sawadm genesis && \
            sawtooth-validator \
                -vv \
                --scheduler parallel \
                --bind network:tcp://eth0:8800 \
                --bind component:tcp://eth0:4004 \
                --endpoint tcp://validator:8800 \
                --peering dynamic \
                --scheduler parallel \
                --network trust



---
  
  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sawtooth-test
  name: validator-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: validator-2
    spec:      
      containers:
      - name: validator-2
        image: thanhtu/sawtooth-validator-optimized:latest
        ports:
        - containerPort: 4004
        command: 
        - bash
        - "-c"
        - |
          sawadm keygen --force && \
            sawadm genesis && \
            sawtooth-validator \
                -vv \
                --scheduler parallel \
                --bind network:tcp://eth0:8800 \
                --bind component:tcp://eth0:4004 \
                --endpoint tcp://validator:8800 \
                --peering dynamic \
                --scheduler parallel \
                --network trust

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sawtooth-test
  name: sawtooth-settings-tp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sawtooth-settings-tp
    spec:      
      containers:
      - name: sawtooth-settings-tp
        image: hyperledger/sawtooth-settings-tp:latest
        command:
        - settings-tp
        - "-C"
        - "tcp://validator:4004"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sawtooth-test
  name: sawtooth-settings-tp-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sawtooth-settings-tp-1
    spec:      
      containers:
      - name: sawtooth-settings-tp-1
        image: hyperledger/sawtooth-settings-tp:latest
        command:
        - settings-tp
        - "-C"
        - "tcp://validator-1:4004"
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sawtooth-test
  name: sawtooth-settings-tp-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sawtooth-settings-tp-2
    spec:      
      containers:
      - name: sawtooth-settings-tp-2
        image: hyperledger/sawtooth-settings-tp:latest
        command:
        - settings-tp
        - "-C"
        - "tcp://validator-2:4004"


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sawtooth-test
  name: sawtooth-rest-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sawtooth-rest-api
    spec:      
      containers:
      - name: sawtooth-rest-api
        image: hyperledger/sawtooth-rest_api:latest
        ports:
         - containerPort: 8080
        command:
        - sawtooth-rest-api
        - "-C"
        - "tcp://validator:4004"
        - "--bind"
        - 0.0.0.0:8080


---
apiVersion: v1
kind: Service
metadata:
  name: sawtooth
  namespace: sawtooth-test
spec:
 selector:
   app: sawtooth-rest-api
 type: NodePort
 ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 38080
