apiVersion: v1
kind: Namespace
metadata:
    name: sawtooth-test

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sawtooth-test
  name: sawtooth-rest-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sawtooth-rest-api
    spec:      
      containers:
      - name: sawtooth-rest-api
        image: hyperledger/sawtooth-rest_api:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        command:
        - sawtooth-rest-api
        - "-C"
        - "tcp://validator:30004"
        - "--bind"
        - 0.0.0.0:8080


---
apiVersion: v1
kind: Service
metadata:
  name: sawtooth-api
  namespace: sawtooth-test
spec:
 selector:
   app: sawtooth-rest-api
 type: NodePort
 ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    # targetPort: 38080
    nodePort: 30080

