apiVersion: v1
kind: Namespace
metadata:
    name: sawtooth-vanilla-test-a

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sawtooth-vanilla-test-a
  name: sawtooth-rest-api
spec:
  selector:
    matchLabels:
      app: sawtooth-rest-api
  replicas: 1
  template:
    metadata:
      labels:
        app: sawtooth-rest-api
    spec:
      nodeSelector:
        node4: node4      
      containers:
      - name: sawtooth-rest-api
        image: hyperledger/sawtooth-rest_api:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        command:
        - sawtooth-rest-api
        - "-C"
        - "tcp://sawtooth.sawtooth-vanilla-test-a:4004"
        - "--bind"
        - 0.0.0.0:8080


---
apiVersion: v1
kind: Service
metadata:
  name: sawtooth-api
  namespace: sawtooth-vanilla-test-a
spec:
 selector:
   app: sawtooth-rest-api
 type: NodePort
 ports:
  - name: endpoint
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32180

